### ISSUE TITLE
Font picker doesn't recognize div with id of font-picker

### ISSUE THREAD

**Issue by arounipa** [samuelmeuli/font-picker#10]
I'm unable to get fontpicker.js to recognize <div id="font-picker">

**Comment by samuelmeuli** [comment]
Are there any errors displayed in the console? Or could you show me the relevant parts of your code?

**Comment by WardBenjamin** [comment]
I fixed this (most recent version) by placing the JS in the footer so that it was placed after the `font-picker` div.

**Comment by arounipa** [comment]
> I fixed this (most recent version) by placing the JS in the footer so that it was placed after the `font-picker` div.

I'll try this.  Thanks!

**Comment by samuelmeuli** [comment]
Yes, the font picker should only be initialized after the DOM has finished parsing. You can achieve that by putting your script at the end of the document `<body>` or by using the `defer` attribute.

I'll add that to the README.

**Comment by arounipa** [comment]
> Yes, the font picker should only be initialized after the DOM has finished parsing. You can achieve that by putting your script at the end of the document `<body>` or by using the `defer` attribute.
> 
> I'll add that to the README.

Thanks!

**Comment by arounipa** [comment]
Putting the javascript at the end fixed it.  Thanks everyone!
