### ISSUE TITLE
setActiveFont doesn't work

### ISSUE THREAD

**Issue by sergeizhukov** [samuelmeuli/font-picker#15]
Hello. Is it correct? When after init of **fontPicker** I try to set font:
```
const fontPicker = new FontPicker(
    YOUR_API_KEY, // Google API key
    "Open Sans", // Default font
    { limit: 30 }, // Additional options
  );

fontPicker.setActiveFont("Ubuntu");
```

I get this:

> FontPicker.js:1 Uncaught TypeError: Cannot read property 'classList' of undefined at t.value (FontPicker.js:1)

Google Chrome (the last version) Version 76.0.3809.100 (Offizieller Build) (64-Bit)
p.s. Getter is works.

**Comment by samuelmeuli** [comment]
This is working for me with the demo (https://font-picker.samuelmeuli.com).

Could you share some more info about your setup?

**Comment by sergeizhukov** [comment]
Now i get not in the list but I see Ubuntu in the list.
![image](https://user-images.githubusercontent.com/44158607/63009050-0926a980-be84-11e9-9c66-45d9f4f630c9.png)
result:
![image](https://user-images.githubusercontent.com/44158607/63009106-2491b480-be84-11e9-9d17-3a6d549decc1.png)

But if i will set default` 'Lato'` and `fontPicker.setActiveFont('Lato');`
Then i see
![image](https://user-images.githubusercontent.com/44158607/63009437-c7e2c980-be84-11e9-9d50-7d519b0e1c9c.png)

Now for resolve it, I use defaultFont via constructor and don't use method`.setActiveFont('');` at all

**Comment by samuelmeuli** [comment]
The component is performing asynchronous calls in the constructor, so the font list won't be built yet if you call `setActiveFont` immediately afterwards. If you want to customize the initial font list, you should do that with the class parameters (e.g. `defaultFamily`). That way, you'll also avoid unnecessary network requests.
