### ISSUE TITLE
Set "Not selected"

### ISSUE THREAD

**Issue by sergeizhukov** [samuelmeuli/font-picker#16]
Hello. How can I set "Not selected" row? 
For example i want to allow for user "reset" the font setting. The row with empty value.

**Comment by samuelmeuli** [comment]
That's currently not possible. I implemented this component to be like the font pickers in word processors like Word or Pages, and since text cannot be displayed without a font, I think it makes sense to always display one in the picker.

What's your use case for this? Are you displaying the picker on a different page than the formatted text?

**Comment by sergeizhukov** [comment]
> What's your use case for this? Are you displaying the picker on a different page than the formatted text?

For example: a web site has variable template system. Every user has own chosen template. Every template has different "default font". User in setting set "default font" or "not selected", he sees the default font (in every case different)

**Comment by samuelmeuli** [comment]
Couldn't you just pass a variable into the font picker constructor?

**Comment by sergeizhukov** [comment]
> Couldn't you just pass a variable into the font picker constructor?
First of all, I have the custom Font xD It's not exists on the google list. But yeah I just use Open Sans "as standard" but on template load another. Everything via constructor, but i thought it kinda isn't Samurai Path.

**Comment by samuelmeuli** [comment]
I'm not sure if I understand. Support for custom fonts is tracked by #17. And with using a variable, I mean something like this:

```js
const API_KEY = "ABC123";
const templateVars = getTemplateVars();

const fontPicker = new FontPicker(API_KEY, templateVars.defaultFont);
```

I don't understand why you're setting the font to Open Sans first?

**Comment by sergeizhukov** [comment]
> I don't understand why you're setting the font to Open Sans first?
1. Because on every template the default font is different.
2. Many of them is out of Google Font (not in the list)

**Comment by samuelmeuli** [comment]
So implementing #17 would resolve this for you?
