### ISSUE TITLE
Font loaded callback

### ISSUE THREAD

**Issue by Nadoedalo** [samuelmeuli/font-picker#18]
Hello
Thanks for the font-picker, it works pretty nice but I have the following issue: 

Currently the onChange function will trigger after the font were selected - but BEFORE it were loaded and actually applied.

I need the callback on when the font is loaded since I'm using fonts with canvas text - and those require manual update to be properly redrawn.

**Comment by samuelmeuli** [comment]
Hi @Nadoedalo, have a look at this issue: https://github.com/samuelmeuli/font-picker-react/issues/17
