### ISSUE TITLE
Webpack and Array.from(fontMap.values());

### ISSUE THREAD

**Issue by Nadoedalo** [samuelmeuli/font-picker#19]
I'm using the same bundle in two different environments(**testing** which is a copy of the full website and **local** which is just the necessary parts to launch the same) and for some weird reason font-picker works fine on local and doesn't work on testing - it doesn't generate the dropdown list properly.

I've checker everything through headers to response and I've debugged to one simple conclusion - this link is generated wrongly:
`https://fonts.googleapis.com/css?family=&subset=latin&text=&font-display=swap`
since it should look like this
`https://fonts.googleapis.com/css?family=Roboto%3Aregular%7CLato%3Aregular%7CMontserrat%3Aregular%7CRoboto+Condensed%3Aregular%7CSource+Sans+Pro%3Aregular%7COswald%3Aregular%7CRaleway%3Aregular%7CRoboto+Mono%3Aregular%7CMerriweather%3Aregular%7CRoboto+Slab%3Aregular%7CPoppins%3Aregular%7CNoto+Sans%3Aregular%7CPT+Sans%3Aregular%7CUbuntu%3Aregular%7CPlayfair+Display%3Aregular%7CMuli%3Aregular%7CPT+Serif%3Aregular%7CLora%3Aregular%7CSlabo+27px%3Aregular%7CTitillium+Web%3Aregular%7CNunito%3Aregular%7CFira+Sans%3Aregular%7CNoto+Serif%3Aregular%7CRubik%3Aregular%7CWork+Sans%3Aregular%7CNanum+Gothic%3Aregular%7CNoto+Sans+JP%3Aregular%7CInconsolata%3Aregular%7CQuicksand%3Aregular&subset=latin&text=RobtLaMnser+CdSucPOwlyihpNTUfD27xmWFkGJIQ&font-display=swap`

Since I didn't saw any changes on the previous response - I've dug into JS
And do you have any idea why with the same **fontMap** input produces different results with **Array.from(fontMap.values());**?
testing:
![fonts_empty](https://user-images.githubusercontent.com/4013151/65732058-c38b0c80-e0d0-11e9-9cda-f25bc3f4074f.png)

and here is the local:
![fonts_full](https://user-images.githubusercontent.com/4013151/65732082-e74e5280-e0d0-11e9-9303-5a7f8981de15.png)

I'm using webpack and babel. It is super-weird that same bundle works differently in different environments.

I had issues with **Map** and Webpack previously.

Any advice on why this happens?

**Comment by samuelmeuli** [comment]
That's really weird.

I assume you're using different builds (dev/prod) on the different environments. Have you tested a production build locally? Can you reproduce the issue there?

**Comment by Nadoedalo** [comment]
Be aware that Array.from is rewritten by prototype.js and it works unreliably with **Map**

I've adjusted the lib - now everything works as expected.

Thank you for attention
Good luck with everything
