### ISSUE TITLE
TypeError: _this2.onChange is not a function

### ISSUE THREAD

**Issue by webmix** [samuelmeuli/font-picker#20]
Hello,

I am trying to implement the lib on a Rails app, with the purpose of being able to select a font in an admin panel to use it later on the front.
My idea is to call another function with `onChange` to get the value of the selected font and add it to a hidden input in my form, in order to save it to the database

Currently doing simple test, I noticed an error on `onChange`

Here is what I got so far :

```
import FontPicker from "font-picker/dist/FontPicker.js";

$(document).on('turbolinks:load', function() {

  const fontPickerTitle = new FontPicker(
    'xxxxxxxxxxxxxxxx',
    "Ubuntu",
    { pickerId: "title" },
    { onChange: console.log('test') }
  );

})
```

On first load, the `console.log('test')` works correctly.
But when I select another font in the dropdown, I got the following error :
```
TypeError: _this2.onChange is not a function
```

Maybe this is due to Rails turbolinks, but I didn't find another way than wrapping the const into `on('turbolinks:load', function()`, otherwise it does not find the markup with the ID of the div `font-picker-title`.

Any clue on what is going on ?

Thanks!

**Comment by samuelmeuli** [comment]
Hi @webmix,

Try this:

```diff
import FontPicker from "font-picker/dist/FontPicker.js";

$(document).on('turbolinks:load', function() {

  const fontPickerTitle = new FontPicker(
    'xxxxxxxxxxxxxxxx',
    "Ubuntu",
    { pickerId: "title" },
-   { onChange: console.log('test') }
+   () => {
+     console.log('test');
+   },
  );
})
```

Let me know if this works for you :)

**Comment by webmix** [comment]
Hi @samuelmeuli !
Thank you so much for your fast answer !

Awesome, that works now !
I didn't know this syntax (not loving much JS :P)

Now I got everything I need, doing the following code works like a charm :
```
$(document).on('turbolinks:load', function() {

  const fontPickerTitle = new FontPicker(
    'xxxxxxxxxxxxxxx',
    "Ubuntu",
    { pickerId: "title" },
    () => {
      if(typeof fontPickerTitle !== 'undefined') {
        console.log(fontPickerTitle.getActiveFont().family);
      }
    },
  );

})
```
Thank you !
