### ISSUE TITLE
Cannot read property 'OPTIONS_DEFAULTS' of undefined  at new FontPicker

### ISSUE THREAD

**Issue by anchetaWern** [samuelmeuli/font-picker#21]
I used the following code:

```
<div id="font-picker"></div>
```

```
const fontPicker = new FontPicker(GOOGLE_API_KEY, "Open Sans", {
    limit: 30
  });
```

I also tried specifying the `pickerId`:

```
<div id="font-picker-bodytext"></div>
```

```
const bodyTextFontPicker = new FontPicker(
    GOOGLE_API_KEY,
    "Open Sans",
    {
      pickerId: "bodytext",
      limit: 25
    }
  );
```

But I get the following error:

```
Cannot read property 'OPTIONS_DEFAULTS' of undefined  at new FontPicker
```

I included the `FontPicker.js` from the `dist` folder.

**Comment by samuelmeuli** [comment]
Hi @anchetaWern,

You'll need to use the file in the `dist-browser` directory (can also be downloaded [here](https://github.com/samuelmeuli/font-picker/releases)). The files in `dist` are for NPM (dependencies are not included in that build because NPM will install them).

**Comment by anchetaWern** [comment]
Thanks! it works now
