### ISSUE TITLE
I want to change the font-picker styles

### ISSUE THREAD

**Issue by tolgaerdonmez** [samuelmeuli/font-picker#24]
I cloned your font-manager repo, I found the source of the styles but I couldn't manage to understand the connection of styles to font-picker.

**Comment by tolgaerdonmez** [comment]
I managed to download the style file using developer tools, then overwrote some styles, but I still believe that there is a such better way that I have no idea about 😃

**Comment by samuelmeuli** [comment]
Font Manager includes default styles in the JavaScript bundle using `rollup-plugin-postcss`. If you want to change them, you can load your own stylesheet and override them. See https://github.com/samuelmeuli/font-picker-react/issues/16

**Comment by tolgaerdonmez** [comment]
Thanks, awesome work btw 👍👍👍
