### ISSUE TITLE
Option keys aren't optional with TypeScript

### ISSUE THREAD

**Issue by tolgaerdonmez** [samuelmeuli/font-picker#25]
```typescript
export interface Options {
    pickerId?: string;
    families?: string[];
    categories?: Category[];
    scripts?: Script[];
    variants?: Variant[];
    filter?: (font: Font) => boolean;
    limit?: number;
    sort?: SortOption;
}
```
it would be better to set options to nullable, because it complains when using the module in typescript
<img width="1051" alt="image" src="https://user-images.githubusercontent.com/45141388/81968032-81451a00-9624-11ea-874d-e1bed99354a0.png">

**Comment by samuelmeuli** [comment]
Thanks for reporting! This should be fixed in [v3.5.1](https://github.com/samuelmeuli/font-picker/releases/tag/v3.5.1).
