### ISSUE TITLE
programmatically add a specified font to the dropdown

### ISSUE THREAD

**Issue by carterax** [samuelmeuli/font-picker#4]
Great plugin you have here saved me a ton of time, How do we add a new font or a set of fonts to the drop down list even after it's rendered on the page.
Thanks a lot :)

**Comment by samuelmeuli** [comment]
Hi there, glad to hear it!

I'm afraid that's currently not possible. I'm going to have a look at how this could be implemented.

**Comment by carterax** [comment]
Thanks a whole lot.

**Comment by samuelmeuli** [comment]
This will be included in the next update :)
