### ISSUE TITLE
Should be appendChild instead of append

### ISSUE THREAD

**Issue by 7wonders** [samuelmeuli/font-picker#5]
```
this.dropdownButton.append
```

**Comment by samuelmeuli** [comment]
May I ask why? Is something not working as expected? Or is it for browser compatibility?

**Comment by 7wonders** [comment]
I'm using it within tizen (Samsung watch face) so I try to keep external
libraries to a minimum. Forgive me if I'm wrong but append requires jquery
whereas appendChild is pure js.

**Comment by samuelmeuli** [comment]
It's actually also available without it ([see MDN](https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/append)).

But I noticed that I'm using `append` and `appendChild` inconsistently, and since the latter is more widely supported, it probably makes sense to use `appendChild` everywhere.

**Comment by 7wonders** [comment]
Thanks! I guess tizens browser hasn't caught up yet :)

**Comment by samuelmeuli** [comment]
v2.2.1 includes the fix. Thanks!
