### ISSUE TITLE
onChange only fires once during initialization

### ISSUE THREAD

**Issue by cookmscott** [samuelmeuli/font-picker#6]
Hey Samuel and friends... My expectation of the below is that foo() will execute each time the active font is changed. In other words, the onChange function of the constructor should fire every time a user selects a new font. However, it seems foo() is only executed once on initialization. 

```
let fontPicker = new FontPicker(
    'keysdgjlkjsdg', // Google API key
    'Open Sans', // default font
    {limit: 20},
    foo()
);    

function foo() {
    console.log ('font changed')
}
```

Let me know if you'd like a fiddle.

**Comment by samuelmeuli** [comment]
Hi @cookmscott,

The problem is that you're executing the function when you pass it to the picker as a paremter. Instead, you should only pass a reference to the function (no parentheses):

```js
let fontPicker = new FontPicker(
    'keysdgjlkjsdg', // Google API key
    'Open Sans', // default font
    {limit: 20},
    foo
);    

function foo() {
    console.log ('font changed')
}
```

Let me know if this works as expected :)

**Comment by samuelmeuli** [comment]
It's probably unexpected behavior that the function also fires on initialization, though. I think I might change that.

**Comment by cookmscott** [comment]
Omahgerd... Simply specifying `foo` as a parameter to the picker works like a charm. Thanks for catching my mistake!
