### ISSUE TITLE
Apply font doesn't work with multiple font pickers

### ISSUE THREAD

**Issue by jede** [samuelmeuli/font-picker#7]
Hi,

Thanks for a great library! I noticed that this line:
https://github.com/samuelmeuli/font-picker/blob/3a4d81b0b8bf916bf5c0a1d73d8735c13287de47/src/font-manager/styles/declarations.ts#L39
Always replaces the whole style. This unfortunately leads to that two different font pickers will overwrite each others styles. So only one font can be applied at once. I guess its possible to work around by just using inline styles, but it would of course be easier wil the apply-font class.

![fontpicker](https://user-images.githubusercontent.com/7389/56204848-ad205580-6048-11e9-88c6-fa4506f08be5.gif)

**Comment by samuelmeuli** [comment]
Thanks for looking into this! It should be fixed in the next version :)
