### ISSUE TITLE
Cannot resolve dependency 'font-picker' in 3.02

### ISSUE THREAD

**Issue by uisupply** [samuelmeuli/font-picker#8]
When I try and run my project using parceljs (which worked with font-picker 2.x) i get this error 'Cannot resolve dependency 'font-picker''

Not sure whats causing it but I took a look at the package.json in node_modules and these paths dont seem to exist:

```
  "main": "dist/font-picker/FontPicker.js",
  "module": "dist/font-picker/FontPicker.es.js",
```

**Comment by samuelmeuli** [comment]
Thanks for reporting this, it should now be fixed. I'm going to release a new version soon, please let me know if it's still not working.
